transfers/models/transfer.py
import datetime
from decimal import Decimal

import sqlalchemy as sa
from sqlalchemy.orm import relationship

from common.db import Base
from transfers.enums import MoneyTransferStatusEnum
from users.models.user import User


class Currency(Base):
    __tablename__ = "currencies"
    name: str = sa.Column(sa.String, primary_key=True, autoincrement=False)


class MoneyTransfer(Base):
    __tablename__ = "money_transfers"
    id: int = sa.Column(sa.Integer, primary_key=True, autoincrement=True)

    originator_id: int = sa.Column(
        sa.Integer, sa.ForeignKey('users.id'), nullable=False)
    receiver_id: int = sa.Column(
        sa.Integer, sa.ForeignKey('users.id'), nullable=False)

    date_modified: datetime.datetime = sa.Column(
        sa.DateTime, onupdate=datetime.datetime.utcnow, nullable=False,
        index=True)
    amount: Decimal = sa.Column(sa.Numeric(precision=12, scale=2),
                                nullable=False)
    currency: str = sa.Column(sa.String, sa.ForeignKey('currencies.name'))
    status: int = sa.Column(sa.Integer, nullable=False)

    originator: User = relationship("User", backref="outgoing_transfers",
                                    foreign_keys=[originator_id])
    receiver: User = relationship("User", backref="incoming_transfers",
                                  foreign_keys=[receiver_id])
    notes: User = relationship("MoneyTransferStaffNote", backref="transfer",
                               order_by="desc(MoneyTransferStaffNote.date_created)")

    def get_status_display(self) -> str:
        return MoneyTransferStatusEnum(self.status).name


class MoneyTransferStaffNote(Base):
    __tablename__ = "money_transfers_staff_notes"
    id: int = sa.Column(sa.Integer, primary_key=True, autoincrement=True)
    created_by_id: int = sa.Column(sa.Integer, sa.ForeignKey('users.id'),
                                   nullable=False)
    money_transfer_id: int = sa.Column(
        sa.Integer, sa.ForeignKey('money_transfers.id'), nullable=False)
    date_created: datetime.datetime = sa.Column(sa.DateTime,
                                                default=datetime.datetime.utcnow,
                                                nullable=False)
    note: str = sa.Column(sa.Text, nullable=False)

    created_by: User = relationship("User", backref="notes")

transfers/views.py
import flask
from flask import render_template, request, Blueprint, abort, redirect, url_for
from flask_login import login_required, current_user

from transfers.data.money_transfer import MoneyTransferPublicData
from transfers.data.note import AddNoteData
from transfers.services import transfer_service

blueprint = Blueprint('transfers', __name__, template_folder='templates')


# List
@blueprint.route('/', methods=["GET"])
@login_required
def list_():
    return render_template("list.html")


# Fetch
@blueprint.route('/fetch_transfers', methods=["GET"])
@login_required
def fetch_transfers():
    page = request.args.get('page', 1, type=int)

    return {
        "result": [MoneyTransferPublicData.from_orm(mt).dict()
                   for mt in transfer_service.get_transfers_paginated(10, page)]
    }


# Details
@blueprint.route('/<int:transfer_id>', methods=["GET"])
@login_required
def transfers_details(transfer_id: int):
    transfer = transfer_service.get_by_id(transfer_id)
    if not transfer:
        raise abort(404)

    return render_template("details.html", transfer=transfer)


@blueprint.route('/<int:transfer_id>/add_note', methods=["POST"])
@login_required
def add_note(transfer_id: int):
    try:
        data = AddNoteData(**request.form)
        transfer_service.add_note(transfer_id, data.note, current_user.get_id())
    except ValueError:
        flask.flash("Note cannot be empty", "error")

    return redirect(url_for("transfers.transfers_details",
                            transfer_id=transfer_id))

transfers/templates/details.html
{% extends "base.html" %}
{% block content %}
    <article>
        <h3>Transfer #{{ transfer.id }}</h3>
        <div>Originator: {{ transfer.originator.username }}</div>
        <div>Receiver: {{ transfer.receiver.username }}</div>
        <div>Amount: {{ transfer.amount }} {{ transfer.currency }}</div>
        <div>Date: {{ transfer.date_modified }}</div>
        <div>Status: {{ transfer.get_status_display() }}</div>
        <div>
            <hr />
            <h3>Notes</h3>
            <table role="grid">
                <tr>
                    <th></th>
                    <th>Date created</th>
                    <th>Created by</th>
                </tr>
                {% for n in transfer.notes %}
                <tr>
                    <td>{{n.note}}</td>
                    <td>{{n.date_created}}</td>
                    <td>{{n.created_by.username}}</td>
                </tr>
                {% else %}
                <tr>
                    <td colspan="3">No notes available</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <hr />
        <form method="post" action="{{ url_for('transfers.add_note', transfer_id=transfer.id) }}">
            <textarea required name="note"></textarea>
            <input type="submit" value="Add">
        </form>
    </article>
{% endblock %}

transfers/templates/list.html
{% extends "base.html" %}
{% block head %}
<script type="text/javascript">
    function transfers_list() {
        return {
            page: 1,
            generate_details_url(transfer_id){
              return "{{ url_for('transfers.list_') }}" + transfer_id
            },
            get_transfers() {
                console.warn("get_transfers");
                if(this.loading){
                    return;
                }
                this.loading = true;
                this.error = null;
                this.transfers = [];
                fetch("{{ url_for('transfers.fetch_transfers') }}?page=" + this.page, {
                    method: 'GET',
                    headers: {'Content-Type': 'application/json'},
                    body: JSON.stringify(this.form_data)
                })
                .then(response => {
                    if(!response.ok){
                        this.error = true;
                    }
                    return response.json()
                })
                .then(data => {
                    this.loading = false;
                    this.transfers = data['result'];
                })
                .catch(data => {
                    this.loading=false;
                })
            }
        }
    }
</script>
{% endblock %}
{% block content %}
    <article>
        <h3>Transfers</h3>
        <table x-data="transfers_list()" x-init="get_transfers()" role="grid">
          <thead>
            <tr>
              <th scope="col">Date modified</th>
              <th scope="col">Originator</th>
              <th scope="col">Amount</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
          <template x-for="transfer in transfers" :key="transfer.id">
            <tr>
              <td x-text="transfer.date_modified"></td>
              <td x-text="transfer.originator.username"></td>
              <td>
                  <span x-text="transfer.amount"></span>
                  <span x-text="transfer.currency"></span>
              </td>
                <td>
                    <a x-bind:href="generate_details_url(transfer.id)">Details</a>
              </td>
            </tr>
        </template>
         <template x-if="loading">
               <tr>
                    <td colspan="3" style="text-align: center;">Loading</td>
                </tr>
         </template>
          </tbody>
        </table>
    </article>
{% endblock %}