users/models/user.py
import sqlalchemy as sa
from sqlalchemy.orm import relationship

from common.db import Base


class User(Base):
    __tablename__ = "users"

    id = sa.Column(sa.Integer, primary_key=True, autoincrement=True)
    username: str = sa.Column(sa.String, unique=True, nullable=False,
                              index=True)
    password: str = sa.Column(sa.String, nullable=False)
    wallets = relationship("Wallet", back_populates="owner")
    is_staff: bool = sa.Column(sa.Boolean, default=False, nullable=False)
    is_active: bool = sa.Column(sa.Boolean, default=False, nullable=False)

    def get_id(self):
        return self.id

    def is_authenticated(self):
        return self.is_staff and self.is_staff

    def is_anonymous(self):
        return not self.is_staff

users/views.py
from flask import render_template, request, abort, Blueprint, redirect, url_for
from flask_login import login_user, login_required, logout_user
from pydantic import ValidationError

from users.data.login_form import LoginData
from users.services import user_service

blueprint = Blueprint('users', __name__, template_folder='templates')


@blueprint.route('/', methods=["GET"])
def login_get():
    return render_template("login.html")


@blueprint.route('/login', methods=["POST"])
def login_post():
    try:
        data = LoginData(**request.json)
        user = user_service.login(data.username, data.password)
        if not user:
            raise abort(404)

        login_user(user)

        return redirect(url_for('transfers.list_'))

    except ValidationError as e:
        return {"form_errors": e.json()}, 400


@blueprint.route('/logout', methods=["GET"])
@login_required
def logout():
    logout_user()
    return redirect(url_for("users.login_get"))

users/templates/login.html
{% extends "base.html" %}
{% block content %}
    <main class="container">
        {% include "partials/login_form.html" %}
    </main>
{% endblock %}

users/templates/partials/login_form.html
{% block head %}
<script type="text/javascript">
    function login_form() {
        return {
            loading: false,
            error: null,
            form_data: {
                username: '',
                password: ''
            },
            login() {
                if(this.loading){
                    return;
                }
                this.loading = true;
                this.error = null;
                fetch("{{ url_for('users.login_post') }}", {
                    method: 'POST',
                    headers: {'Content-Type': 'application/json'},
                    body: JSON.stringify(this.form_data),
                    redirect: 'follow'
                })
                .then(response => {
                    if(response.redirected){
                        window.location.href = response.url;
                    }
                    if(!response.ok){
                        this.error = true;
                    }
                    return response.json()
                })
                .then(data => {
                    this.loading = false;
                })
                .catch(data => {
                    this.loading=false;
                })
            }
        }
    }
</script>
{% endblock %}
<h2>Login</h2>
<form action="{{ url_for('users.login_post') }}" method="post" x-data="login_form()" @submit.prevent="login">
    <label for="username">Username</label><input x-bind:aria-invalid="error ? 'true': null" x-model="form_data.username" id="username" name="username" type="text" required>
    <label for="password">Password</label><input x-bind:aria-invalid="error ? 'true': null" x-model="form_data.password" id="password" name="password" type="password" required>
    <button id="login-btn" type="submit" x-show="!loading" :disabled="loading">Login</button>
    <button  type="submit" aria-busy="true" class="secondary" x-show="loading"></button>
</form>